### PR TITLE
2016 1st quarter update

### PR DESCRIPTION
**Pull request by SideshowN**

### CODE REVIEW

**Comment by SideshowN** [comment]
[batcountry.zip](https://github.com/rbhp-espher/rbhp/files/170668/batcountry.zip)
Here is a pro drums fix for batcountry although it may not work.  Reason is in a text file.

**Comment by SideshowN** [comment]
[yougiveloveabadname.zip](https://github.com/rbhp-espher/rbhp/files/170669/yougiveloveabadname.zip)

Here is one for Bon Jovie "You give love a bad name" from Lego Rock Band.

**Comment by SideshowN** [comment]
[spacetruckin.zip](https://github.com/rbhp-espher/rbhp/files/170670/spacetruckin.zip)

Here is one from Deep Purple "SpaceTruckin"

**Comment by SideshowN** [comment]
[Cherry Waves.zip](https://github.com/rbhp-espher/rbhp/files/170708/Cherry.Waves.zip)

Here is one for Deftones "CherryWaves"

**Comment by SideshowN** [comment]
[Hole in the Earth.zip](https://github.com/rbhp-espher/rbhp/files/170673/Hole.in.the.Earth.zip)

Here is one for Deftones "Hole in the Earth"

**Comment by SideshowN** [comment]
[sciencegeniusgirl.zip](https://github.com/rbhp-espher/rbhp/files/170710/sciencegeniusgirl.zip)

Here is one for Freezepop "ScienceGeniusGirl"

**Comment by SideshowN** [comment]
[breakout.zip](https://github.com/rbhp-espher/rbhp/files/170711/breakout.zip)

Here is one for Foo Fighters "Breakout"

**Comment by SideshowN** [comment]
[Emenius Sleepus.zip](https://github.com/rbhp-espher/rbhp/files/170712/Emenius.Sleepus.zip)

Here is one for Green Day "Emenius Sleepus"

**Comment by SideshowN** [comment]
[Homecoming.zip](https://github.com/rbhp-espher/rbhp/files/170714/Homecoming.zip)

I got one for Green Day "Homecoming"

**Comment by SideshowN** [comment]
[theclairvoyant.zip](https://github.com/rbhp-espher/rbhp/files/170715/theclairvoyant.zip)

Here is one for Iron Maiden "The Clairvoyant"

**Comment by SideshowN** [comment]
[InTouch.zip](https://github.com/rbhp-espher/rbhp/files/170742/InTouch.zip)

The Cars "Im in touch with your world".  This is one of the worst pro drum charts I have ever seen.  Lot's of changes to this chart.

**Comment by SideshowN** [comment]
[icarus.zip](https://github.com/rbhp-espher/rbhp/files/170743/icarus.zip)

Kansas "Icarus"

**Comment by SideshowN** [comment]
[differentpeople.zip](https://github.com/rbhp-espher/rbhp/files/171168/differentpeople.zip)

I've got a few more today.  To start off here is No Doubt "Different People"

**Comment by SideshowN** [comment]
[Deep.zip](https://github.com/rbhp-espher/rbhp/files/171169/Deep.zip)

Pearl Jam "Deep"

**Comment by SideshowN** [comment]
[Porch.zip](https://github.com/rbhp-espher/rbhp/files/171170/Porch.zip)

Pearl Jam "Porch"

**Comment by SideshowN** [comment]
[debaser.zip](https://github.com/rbhp-espher/rbhp/files/171171/debaser.zip)

Pixies "Debaser"

**Comment by SideshowN** [comment]
[We Are the Champions(Lego).zip](https://github.com/rbhp-espher/rbhp/files/171175/We.Are.the.Champions.Lego.zip)

Queen "We Are the Champions" , the Lego Rock Band version.

**Comment by SideshowN** [comment]
[theyreredhot.zip](https://github.com/rbhp-espher/rbhp/files/171177/theyreredhot.zip)

Red Hot Chili Peppers "Theyareredhot"

**Comment by SideshowN** [comment]
[blackholesun.zip](https://github.com/rbhp-espher/rbhp/files/171180/blackholesun.zip)

Soundgarden "Blackholesun"

**Comment by SideshowN** [comment]
[hammerhead.zip](https://github.com/rbhp-espher/rbhp/files/171181/hammerhead.zip)

Finally I have The Offspring "Hammerhead"

If I find any more problematic songs I'll post.

**Comment by SideshowN** [comment]
I found another one:

[Holiday.zip](https://github.com/rbhp-espher/rbhp/files/171249/Holiday.zip)

Green Day "Holiday".

**Comment by rbhp-espher** [comment]
I'm closing the pull request because I don't think this was done right, but I'll try to pull these and merge them 'properly' here this week.

**Pull request closed without merging**
