### PR TITLE
Four new Keys upgrades

### PR DESCRIPTION
**Pull request by LinosM**
When You Were Young - RB1
Rebel Yell - DLC 2009
Rize of the Fenix - DLC 2015
Spaceman - DLC 2008

### CODE REVIEW

**Comment by NuclearFej** [comment]
It would be really cool if this got merged. It's been a while. In the meantime, I'm just going to download your fork for my club, since those are some really cool charts!

**Comment by FatHa1p3rt** [comment]
^ Seconded. I've had these key upgrades for months now but I'd still love to see a formal update. I feel like just letting these upgrades sit here discourages people from adding key upgrades in the future.

**Comment by LinosM** [comment]
Yeah, there are more upgrades I want to do. But I don't know anything about creating the upgrade dtas so that's why I leave these here and create local rb3 versions for myself.

I already have some more in the works, so if I figure it out I will probably release them all publicly on the Forum.

**Comment by FatHa1p3rt** [comment]
If it would be helpful to you at all, I'm currently working on a spreadsheet that outlines which legacy DLC songs have keys in the actual song and which ones don't. I figured I would post it on the forums to make it easier for people to see which songs need upgrades and which ones don't. I can send it your way if it would be of any use.

**Comment by LinosM** [comment]
Sure go ahead, it sounds useful

**Comment by rbhp-espher** [comment]
I know I've been super quiet for a while but I legit have not had cycles to spare for any of this. I've had people ping me about random things, like the tiny.cc link dying, etc., and even trying to fix/update that stuff has just been too low priority for me. I'm going to see if I can dive back in at some point over the next couple of months and am hopeful I can, if only in a sort of general maintenance role (I've considered trying to dive back in to RBN charting but my 360's USB ports acting up so I can't do any 'live' testing or video recording). 

As for the upgrades.dta files, creating them is pretty easy - the file basically has the following format:

(songshortname
   (upgrade_version 1)
   (midi_file "songs_upgrades/songshortname_plus.mid")
   (song_id ###)
)

**Comment by rbhp-espher** [comment]
I went ahead and merged these just to keep the projects in sync, but I will have to see if I can somehow get the songs.dta files for these tracks (so that I can edit them to add the keys/real_keys parts) and build upgrades.dta files, at least for the ones that are net new.

**Comment by LinosM** [comment]
Oh I can get that no problem, here are the original unmodified ones. I got the Spaceman one from a 3 pack though, not sure if that'll work
[dtas.zip](https://github.com/rbhp-espher/rbhp/files/835585/dtas.zip)

**Comment by rbhp-espher** [comment]
All you need to do with the three-pack ones is split them into three individual files, so that's no problem. I'll try to put them together tonight and update it again.

**Pull request merged**
